export const text = {
	ui: {
		empty: ['Empty', 'Vacío', 'Vide', 'Vazio', 'Vuoto', 'Leer', '空き', '빈 슬롯', '空位', 'Pusty'],
		deploy: ['Deploy', 'Desplegar', 'Déployer', 'Implantar', 'Schierare', 'Platzieren', '配置', '배치', '部署', 'Rozmieść'],
		deploying: ['Deploying', 'Desplegando', 'Déploiement', 'Implantando', 'Schierando…', 'Platzieren…', '配置中', '배치 중', '部署中', 'Rozmieszczanie'],
		retire: ['Retire', 'Retirar', 'Rappeler', 'Retirar', 'Ritirare', 'Zurückziehen', '撤退', '철수', '撤退', 'Wycofaj'],
		info: ['Data', 'Datos', 'Infos', 'Dados', 'Dati', 'Daten', 'データ', '데이터', '数据', 'Dane'],
		nextWave: ['Next wave', 'Siguiente oleada', 'Prochaine vague', 'Próxima onda', 'Prossima ondata', 'Nächste Welle', '次のウェーブ', '다음 웨이브', '下一波', 'Następna Fala'],
		autoWave: ['Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'Auto', 'オート', '오토', '自动', 'Auto'],
		autoWaveUp: ['up to wave', 'hasta oleada', 'jusqu’à vague', 'até a onda', 'fino a ondata', 'bis Welle', 'まで自動進行', '까지 자동 진행', '打到第', 'Do Fali'],
		autoWaveLocked: ['Not available', 'No disponible', 'Indisponible', 'Indisponível', 'Non disponibile', 'Nicht verfügbar', '利用不可', '사용 불가', '不可用', 'Niedostępne'],
		autoWaveUnlimited: ['Unlimited', 'Ilimitado', 'Illimité', 'Ilimitado', 'Illimitato', 'Unbegrenzt', '無制限', '무제한', '无限', 'Bez Limitu'],
		health: ['Health', 'Salud', 'Santé', 'Vida', 'Salute', 'Gesundheit', 'HP', '체력', '生命', 'Zdrowie'],
		armor: ['Armor', 'Armadura', 'Armure', 'Armadura', 'Armatura', 'Rüstung', 'アーマー', '방어력', '护甲', 'Pancerz'],
		gold: ['Gold', 'Oro', 'Or', 'Ouro', 'Oro', 'Gold', 'ゴールド', '골드', '金币', 'Złoto'],
		speed: ['Speed', 'Velocidad', 'Vitesse', 'Velocidade', 'Velocità', 'Geschw.', 'スピード', '속도', '速度', 'Prędkość'],
		power: ['Power', 'Poder', 'Puissance', 'Poder', 'Potenza', 'Kraft', 'パワー', '파워', '力量', 'Moc'],
		regen: ['Regen.', 'Regen.', 'Régé.', 'Regen.', 'Rigen.', 'Reg.', '再生', '재생', '再生', 'Regen.'],
		stun: ['Stun', 'Aturd.', 'Étourd.', 'Atordo.', 'Stord.', 'Betäub.', '気絶', '기절', '眩晕', 'Ogłusz.'],
		slow: ['Slow', 'Ralenti.', 'Lent.', 'Lento.', 'Rallen.', 'Verlang.', '減速', '감속', '减速', 'Spow.'],
		burn: ['Burn', 'Quemad.', 'Brul.', 'Queim.', 'Scott.', 'Verbren.', 'やけど', '화상', '燃烧', 'Poparz.'],
		poison: ['Poison', 'Enven.', 'Empois.', 'Enven.', 'Avvel.', 'Vergift.', '毒', '중독', '中毒', 'Zatru.'],
		vulnerable: ['Able', 'Apto', 'Vuln', 'Apto', 'Vuln', 'Verw', '弱い', '취약', '脆弱', 'Podat.'],
		resistant: ['Res', 'Res', 'Rés', 'Res', 'Res', 'Res', '強い', '강함', '抗性', 'Odp.'],
		invisible: ['Invisible', 'Invisible', 'Invisible', 'Invisível', 'Invisibile', 'Unsichtbar', '透明', '투명', '隐形', 'Niewidzialny'],
		effect: ['Effect', 'Efecto', 'Effet', 'Efeito', 'Effetto', 'Effekt', '効果', '효과', '效果', 'Efekt'],
		yes: ['Yes', 'Sí', 'Oui', 'Sim', 'Sì', 'Ja', 'はい', '예', '是', 'Tak'],
		no: ['No', 'No', 'Non', 'Não', 'No', 'Nein', 'いいえ', '아니요', '否', 'Nie'],
		loading: ['Loading', 'Cargando', 'Chargement', 'Carregando', 'Caricamento', 'Laden', 'ロード中', '로딩중', '加载中', 'Ładowanie'],
		locked: ['Locked', 'Bloqueado', 'Verrouillé', 'Bloqueado', 'Bloccato', 'Gesperrt', 'ロック中', '잠금됨', '已锁定', 'Zablok.'],
		save: ['Save team', 'Guardar equipo', 'Enregistr. l’équipe','Salvar equipe', 'Salvare la squadra', 'Team speichern', 'チームを保存する', '팀 저장', '保存队伍', 'Zapisz drużynę'],
		import: ['Load team', 'Cargar equipo', 'Charger l’équipe', 'Carregar equipe', 'Caricare la squadra', 'Team laden', 'チームを読み込む', '팀 불러오기', '加载队伍', 'Wczytaj drużynę'],
		savedTeam: ["Saved Team", "Equipo guardado", "Équipe sauvegardée", "Equipe salva", "Squadra salvata", "Gespeichertes Team", "保存されたチーム", "저장된 팀", "已保存的队伍", "Zapisana drużyna"],
		loadTeam: ["Loaded Team", "Equipo cargado", "Équipe chargée", "Equipe carregada", "Squadra caricata", "Geladenes Team", "読み込まれたチーム", "불러온 팀", "已加载的队伍", "Wczytana drużyna"],
		helping: [
		  	"IS HELPING",
		  	"ESTÁ AYUDANDO",
		  	"AIDE",
		  	"ESTÁ AJUDANDO",
		  	"STA AIUTANDO",
		  	"HILFT",
		  	"助けている",
		  	"도움을 주고 있음",
		  	"正在协助",
			"POMAGA",
		],
		waveManager: [
			"wave manager",
			"gestor oleadas",
			"gestion vagues",
			"gestor ondas",
			"gestore ondate",
			"Wellen Manager",
			"ウェーブ マネージャー",
			"웨이브 매니저",
			"波次 管理",
			"Menadżer fal"
		],
		trueDamage: [
			"True Damage",
			"Daño real",
			"Dégâts réels",
			"Dano real",
			"Danno reale",
			"Direkter Schaden",
			"真のダメージ",
			"실제 피해",
			"真实伤害",
			"Prawdziwe obrażenia"
		],
		overdamage: [
			"Overdamage",
			"Daño excedente",
			"Dégâts excessifs",
			"Dano excedente",
			"Danno eccessivo",
			"Über Schaden",
			"オーバーダメージ",
			"과잉 피해",
			"超额伤害",
			"Nadwyżka obrażeń"
		],
	},
	pokemon: {
		title: ['Unit Data', 'Datos', 'Données Unité', 'Dados Unidade', 'Dati Unità', 'Einheiteninformation', 'ユニットデータ', '유닛 데이터', '单位数据', 'Dane Jednostki'],
		power: ['Power', 'Poder', 'Puissance', 'Poder', 'Potenza', 'Kraft', 'パワー', '파워', '力量', 'Moc'],
		speed: ['Recharge', 'Recarga', 'Récupération', 'Recarga', 'Ricarica', 'Aufladen', 'リチャージ', '재충전', '充能', 'Przeładowanie'],
		critical: ['Critical', 'Crítico', 'Critique', 'Crítico', 'Critico', 'Kritische Chance', 'クリティカル', '치명타', '暴击', 'Krytyczne'],
		range: ['Range', 'Alcance', 'Portée', 'Alcance', 'Portata', 'Reichweite', '射程', '사거리', '射程', 'Zasięg'],
		rangeType: ['Shape', 'Forma', 'Forme', 'Forma', 'Forma', 'Form', '形状', '형태', '形状', 'Kształt'],
		terrain: ['Terrain', 'Terreno', 'Terrain', 'Terreno', 'Terreno', 'Terrain', '地形', '지형', '地形', 'Teren'],
		attackType: ['Target', 'Objetivo', 'Cible', 'Alvo', 'Bersaglio', 'Ziel', 'ターゲット', '대상', '目标', 'Cel'],
		single: ['Single Target', 'Monobjetivo', 'Cible Unique', 'Alvo Único', 'Bersaglio Singolo', 'Einzelziel', '単体攻撃', '단일 대상', '单体目标', 'Pojedynczy cel'],
		area: ['Area', 'Área', 'Zone', 'Área', 'Area', 'Fläche', '範囲', '범위', '范围', 'Obszar'],
		circle: ['Circle', 'Círculo', 'Cercle', 'Círculo', 'Cerchio', 'Kreis', '円形', '원형', '圆形', 'Okrąg'],
		donut: ['Ring', 'Anillo', 'Anneau', 'Anel', 'Anello', 'Ring', 'リング', '고리형', '环形', 'Pierścień'],
		cross: ['Cross', 'Cruz', 'Croix', 'Cruz', 'Croce', 'Plus-Form', '十字', '십자형', '十字', 'Krzyż'],
		xShape: ['X Shape', 'X', 'X', 'X', 'X', 'X-Form', 'Ｘ形', 'X자형', 'X形', 'X'],
		horizontalLine: ['Horizontal Line', 'Línea Horizontal', 'Ligne Horizontale', 'Linha Horizontal', 'Linea Orizzontale', 'Horizontale Linie', '横線', '가로선', '横线', 'Linia Pozioma'],
		verticalLine: ['Vertical Line', 'Línea Vertical', 'Ligne Verticale', 'Linha Vertical', 'Linea Verticale', 'Vertikale Linie', '縦線', '세로선', '竖线', 'Linia Pionowa'],
		lvlUp: ['Level Up', '+ Nivel', 'Niveau +', '+ Nível', '+ Livello', 'Level Up', 'レベルアップ', '레벨업', '升级', 'Poziom +'],
		current: ['Current', 'Actual', 'Actuel', 'Atual', 'Attuale', 'Aktuell', '現在の', '현재의', '当前', 'Aktualny'],
		ricochets: ['Ricochets', 'Rebotes', 'Ricochets', 'Rebotes', 'Rimbalzi', 'Abpraller', '跳ね返り', '튀기', '反弹', 'Rykoszet'],
		projectiles: ['projectiles', 'proyectiles', 'projectiles', 'projéteis', 'proiettili', 'Projektile', '弾丸', '투사체', '投射物', 'pociski'],
		notStack: ['Does not stack', 'No se acumula', "Ne s'accumule pas", 'Não se acumula', 'Non si accumula', 'Stackt sich nicht', 'たまらない', '쌓이지 않음', '不叠加', 'Nie kumuluje się'],
		noItem: ['no item', 'sin objeto', "pas d'objet", 'nenhum item', 'nessun oggetto', 'kein Gegenstand', 'アイテムなし', '아이템 없음', '無道具', 'brak przedmiotu'],
		noItemDescription: [
		  	"No item equipped currently.",
		  	"No hay ningún objeto equipado actualmente.",
		  	"Aucun objet n’est actuellement équipé.",
		  	"Nenhum item está equipado no momento.",
		  	"Nessun oggetto è attualmente equipaggiato.",
		  	"Derzeit ist kein Item ausgerüstet.",
		  	"現在、装備中のアイテムはありません。",
		  	"현재 장착된 아이템이 없습니다.",
		  	"当前未装备任何道具。",
			"Obecnie nie masz wyposażonego żadnego przedmiotu.",
		],
	},
	profile: {
		title: ['Profile', 'Perfil', 'Profil', 'Perfil', 'Profilo', 'Profil', 'プロフィール', '프로필', '个人资料', 'Profil'],
		stats: {
			0: ['Time played', 'Tiempo jugado', 'Temps de jeu', 'Tempo de jogo', 'Tempo di gioco', 'Spielzeit', 'プレイ時間', '플레이 시간', '游玩时间', 'Czas gry'],
			1: ['Stars earned', 'Estrellas ganadas', 'Étoiles gagnées', 'Estrelas ganho', 'Stelle ottenute', 'Sterne verdient', '獲得スター', '획득 별', '获得星数', 'Zdobyte gwiazdki'],
			2: ['Pokémon owned', 'Pokémon obtenidos', 'Pokémon possédés', 'Pokémon obtidos', 'Pokémon posseduti', 'Pokémon im Besitz', '所持ポケモン', '보유 권속', '拥有的宝可梦', 'Posiadane Pokémony'],
			3: [
			   	"Shiny Pokémon",
			  	"Pokémon variocolor",
			  	"Pokémon chromatique",
			  	"Pokémon Shiny",
			  	"Pokémon Shiny",
			  	"Schillerndes Pokémon",
			  	"色違いポケモン",
			  	"색이 다른 권속",
			  	"闪光宝可梦",
				"Pokémony shiny",
			],
			4: ['Highest level', 'Nivel más alto', 'Niveau le plus élevé', 'Nível mais alto', 'Livello più alto', 'Höchstes Level', '最高レベル', '최고 레벨', '最高等级', 'Najwyższy poziom'],
			5: ['Total levels', 'Niveles totales', 'Niveaux totaux', 'Níveis totais', 'Livelli totali', 'Gesamtlevel', '合計レベル', '총 레벨', '总等级', 'Suma poziomów'],
			6: ['Total gold', 'Oro total', 'Or total', 'Ouro total', 'Oro totale', 'Gesamtgold', '総ゴールド', '총 골드', '总金币', 'Łączne złoto'],
			7: [
			  	"Unlocked items",
			  	"Objetos desbloqueados",
			  	"Objets débloqués",
			  	"Itens desbloqueados",
			  	"Oggetti sbloccati",
			  	"Freigeschaltete Gegenstände",
			  	"アンロックされたアイテム",
			  	"잠금 해제된 아이템",
			  	"已解锁的道具",
				"Odblokowane przedmioty",
			],
			8: ['Waves completed', 'Oleadas completadas', 'Vagues complétées', 'Ondas concluídas', 'Ondate completate', 'Abgeschlossene Wellen', 'クリア波数', '완료 웨이브', '完成波数', 'Ukończone fale'],
			9: ['Highest hit', 'Mayor golpe', 'Coup le plus fort', 'Maior golpe', 'Colpo più potente', 'Stärkster Treffer', '最大ヒット', '최대 타격', '最高伤害', 'Największe obrażenia'],
			10: ['Defeated enemies', 'Enemigos derrotados', 'Ennemis vaincus', 'Inimigos derrotados', 'Nemici sconfitti', 'Besiegte Feinde', '撃破数', '처치한 적', '击败敌人', 'Pokonani wrogowie'],
			11: ['Species defeated', 'Especies derrotadas', 'Espèces vaincues', 'Espécies derrotadas', 'Specie sconfitte', 'Besiegte Arten', '倒した種類', '처치한 종', '击败的种类', 'Pokonane gatunki'],
			12: ['Stuns applied', 'Aturdimientos aplicados', 'Étourdissements appliqués', 'Atordoamentos aplicados', 'Stordimenti applicati', 'Betäubungen angewendet', 'スタン付与', '기절 적용', '眩晕次数', 'Nałożone ogłuszenia'],
			13: ['Slows applied', 'Ralentizaciones aplicadas', 'Ralentissements appliqués', 'Retardos aplicados', 'Rallentamenti applicati', 'Verlangsamungen angewendet', 'スロー付与', '감속 적용', '减速次数', 'Nałożone spowolnienia'],
			14: ['Burns applied', 'Quemaduras aplicadas', 'Brulures appliquées', 'Queimaduras aplicadas', 'Scottature applicate', 'Verbrennungen angewendet', '火傷付与', '화상 적용', '灼烧次数', 'Nałożone poparzenia'],
			15: ['Poisons applied', 'Venenos aplicados', 'Poisons appliqués', 'Venenos aplicados', 'Veleni applicati', 'Gifte angewendet', '毒付与', '중독 적용', '中毒次数', 'Nałożone zatrucia'],
			16: ['Curses applied', 'Maldiciones aplicadas', 'Malédictions appliquées', 'Maldições aplicadas', 'Maledizioni applicate', 'Flüche angewendet', '呪い付与', '저주 적용', '诅咒次数', 'Nałożone klątwy'],
			17: ['Resets', 'Reinicios', 'Réinitialisations', 'Reinicializações', 'Reset', 'Zurücksetzungen', 'リセット', '리셋', '重置次数', 'Resety'],
			18: ["Stolen Gold by Persian", "Oro robado por Persian", "Or volé par Persian", "Ouro roubado por Persian", "Oro rubato da Persian", "Gold gestohlen mit Snobilikat", "ペルシアンに盗まれた金", "페르시안에게 도난당한 금", '被貓老大偷走的金幣', 'Złoto skradzione przez Persiana'],
			19: [
				"Max Gold/Wave",
				"Oro máx./Oleada",
				"Or max./Vague",
				"Ouro máx./Onda",
				"Oro max./Ondata",
				"Max. Gold/Welle",
				"最大ゴールド／ウェーブ",
				"최대 골드/웨이브",
				"最大金币/波次",
				"Maks. złota/fala",
			],
			20: [
			  	"Max Gold/Time",
			  	"Oro máx./Tiempo",
			  	"Or max./Temps",
			  	"Ouro máx./Tempo",
			  	"Oro max./Tempo",
			  	"Max. Gold/Zeit",
			  	"最大ゴールド／時間",
			  	"최대 골드/시간",
			  	"最大金币/时间",
				"Maks. złota/czas",
			],
		},
		delete: [
		  	"Delete the data from this statistic?",
		  	"¿Borrar los datos de esta estadística?",
		  	"Supprimer les données de cette statistique ?",
		  	"Apagar os dados desta estatística?",
		  	"Cancellare i dati di questa statistica?",
		  	"Die Daten dieser Statistik löschen?",
		  	"この統計のデータを削除しますか？",
		  	"이 통계의 데이터를 삭제하시겠습니까?",
		  	"要删除此统计的数据吗？",
			"Usunąć dane z tej statystyki?",
		]
	},
	box: {
		title: ['Team Management', 'Gestión de Equipo', 'Gestion d’équipe', 'Gestão de Equipe', 'Gestione Squadra', 'Teamverwaltung', 'チーム管理', '팀 관리', '团队管理', 'Zarządzanie drużyną'],
		add: ['Add Unit', 'Añadir', 'Ajouter', 'Adicionar', 'Aggiungi', 'Hinzufügen', 'ユニット追加', '유닛 추가', '添加单位', 'Dodaj'],
		remove: ['Remove Unit', 'Retirar', 'Retirer', 'Remover', 'Rimuovi', 'Entfernen', 'ユニット削除', '유닛 제거', '移除单位', 'Usuń'],
		removeAll: ['Remove All', 'Ret. Todo', 'Tout ret.', 'Rem. Tudo', 'Rim. Tutto', 'Alle entf.', 'すべて削除', '모두 제거', '全部移除', 'Wyczyść'],
		team: ['In team', 'En grupo', 'Dans l’équipe', 'Na equipe', 'In squadra', 'Im Team', 'チームにいる', '팀에 있음', '队伍中', 'W drużynie'],
		alphabetical: ['Alphabetical', 'Alfabético', 'Alphabétique', 'Alfabético', 'Alfabetico', 'Alphabetisch', 'アルファベット順', '알파벳순', '按字母排序', 'Alfabetycznie'],
		level: ['By Level', 'Nivel', 'Par niveau', 'Por Nível', 'Per Livello', 'Nach Level', 'レベル順', '레벨순', '按等级', 'Według poziomu'],
		ability: ['Ability', 'Habilidad', 'Talent', 'Habilidade', 'Abilità', 'Fähigkeit', 'とくせい', '특성', '特性', 'Umiejętności'],
		grass: ['First Grass', 'Primera Hierba', 'Première Herbe', 'Primeira Grama', 'Prima Erba', 'Gras zuerst', '最初の草', '첫 번째 풀', '最初的草', 'Najpierw Trawa'],
		water: ['First Water', 'Primero Agua', 'Première Eau', 'Primeira Água', 'Prima Acqua', 'Wasser zuerst', '最初の水', '첫 번째 물', '最初的水', 'Najpierw Woda'],
		mountain: ['First Mountain', 'Primero Montaña', 'Prem. Montagne', 'Prim. Montanha', 'Prima Montagna', 'Berg zuerst', '最初の山', '첫 번째 산', '最初的山', 'Najpierw Góry'],
		grassTab: ['grass', 'hierba', 'herbe', 'grama', 'erba', 'Gras', '草', '풀', '草', 'trawa'],
		waterTab: ['water', 'agua', 'eau', 'água', 'acqua', 'Wasser', '水', '물', '水', 'woda'],
		mountainTab: ['mountain', 'montaña', 'montagne', 'montanha', 'montagna', 'Berg', '山', '산', '山', 'góry'],
		fossilTab: ['fossil', 'fósil', 'fossile', 'fóssil', 'fossile', 'Fossil', '化石', '화석', '化石', 'skamielina'],
		allTab: ['all', 'todos', 'tous', 'todos', 'tutti', 'Alle', '全員', '모두', '全部', 'wszyscy'],
		power: ['Power', 'Poder', 'Puissance', 'Poder', 'Potenza', 'Kraft', 'パワー', '파워', '力量', 'Moc'],
		speed: ['Recharge', 'Recarga', 'Récupération', 'Recarga', 'Ricarica', 'Nachladen', 'リチャージ', '재충전', '充能', 'Przeładowanie'],
		range: ['Range', 'Alcance', 'Portée', 'Alcance', 'Portata', 'Reichweite', '射程', '사거리', '射程', 'Zasięg'],
		shiny: ["Shiny","Variocolor","Chromatique","Shiny","Shiny","Schillernd","色違い","색이 다른 권속","闪光", "Shiny"]
	},
	changeName: {
		title: [
			"Add Nickname",
			"Añadir apodo",
			"Ajouter un surnom",
			"Adicionar apelido",
			"Aggiungi soprannome",
			"Spitznamen hinzufügen",
			"ニックネームを追加する",
			"별명 추가",
			"添加昵称",
			"Dodaj Pseudonim",
		],
		rename: [
			"Rename",
			"Renombrar",
			"Renommer",
			"Renomear",
			"Rinominare",
			"Umbenennen",
			"名前を変更する",
			"이름 변경",
			"重命名",
			"Zmień nazwę",
		]
	},
	inventory: {
		title: ['Inventory', 'Inventario', 'Inventaire', 'Inventário', 'Inventario', 'Inventar', 'インベントリ', '인벤토리', '物品栏', 'Ekwipunek'],
		noItem: ['no item', 'sin objeto', "pas d'objet", 'nenhum item', 'nessun oggetto', 'kein Gegenstand', 'アイテムなし', '아이템 없음', '無道具', 'brak przedmiotu'],
		noItemDescription:[
			"No item selected currently.",
			"No hay ningún objeto seleccionado actualmente.",
			"Aucun objet n’est actuellement sélectionné.",
			"Nenhum item está selecionado no momento.",
			"Nessun oggetto è attualmente selezionato.",
			"Derzeit ist kein Item ausgewählt.",
			"現在、選択されているアイテムはありません。",
			"현재 선택된 아이템이 없습니다.",
			"当前未选择任何道具。",
			"Obecnie nie masz wybranego żadnego przedmiotu."
		],
	},
	shop: {
		title: ['Shop', 'Tienda', 'Boutique', 'Loja', 'Negozio', 'Shop', 'ショップ', '상점', '商店', 'Sklep'],
		sold: ['Sold', 'Agotado', 'Vendu', 'Vendido', 'Esaurito', 'Ausverkauft', '売り切れ', '매진', '售罄', 'Wyprzedane'],
		purchase: ['Purchase', 'Comprar', 'Acheter', 'Comprar', 'Acquista', 'Kaufen', '購入', '구매', '购买', 'Kup'],
		prompt: ['Buy something good', 'Compra algo bueno', 'Acheter quelque chose de bien', 'Compre algo bom', 'Compra qualcosa di buono', 'Kauf etwas Gutes', '良いものを買う', '좋은 것을 사라', 'Kup coś dobrego'],
		new: [
			'New Pokémon obtained!',
			'¡Nuevo Pokémon obtenido!',
			'Nouveau Pokémon obtenu !',
			'Novo Pokémon obtido!',
			'Nuovo Pokémon ottenuto!',
			'Neues Pokémon erhalten!',
			'新しいポケモンを入手！',
			'새 권속을 획득!',
			'获得了新的宝可梦！',
			'Zdobyto nowego Pokémona!',
		],
		egg: [
		  	"Contains a random Pokémon.",
		  	"Contiene un Pokémon aleatorio.",
		  	"Contient un Pokémon aléatoire.",
		  	"Contém um Pokémon aleatório.",
		  	"Contiene un Pokémon casuale.",
		  	"Enthält ein zufälliges Pokémon.",
		  	"ランダムなポケモンが入っている。",
		  	"무작위 권속이 들어 있습니다.",
		  	'包含一隻隨機的寶可夢',
			"Zawiera losowego Pokémona.",
		],
		eggName: [
			"Egg",
			"Huevo",
			"Œuf",
			"Ovo",
			"Uovo",
			"Ei",
			"タマゴ",
			"알",
			"蛋",
			"Jajo"
		]
	},
	map: {
		title: ['Map', 'Mapa', 'Carte', 'Mapa', 'Mappa', 'Karte', 'マップ', '맵', '地图', 'Mapa'],
		wave: ['Wave', 'Oleada', 'Vague', 'Onda', 'Ondata', 'Welle', 'ウェーブ', '웨이브', '波次', 'Fala'],
		waves: ['Waves', 'Oleadas', 'Vagues', 'Ondas', 'Ondate', 'Wellen', 'ウェーブ数', '웨이브 수', '波次数', 'Liczba fal'],
		select: ['Route Selection', 'Selección de Ruta', 'Sélection de route', 'Seleção de Rota', 'Selezione zona', 'Routenauswahl', 'ルート選択', '경로 선택', '路线选择', 'Wybór drogi'],
		waveCompleted: ['Wave Completed', 'Oleada Completada', 'Vague terminée', 'Onda Concluída', 'Ondata completata', 'Welle abgeschlossen', 'ウェーブ完了', '웨이브 완료', '波次完成', 'Fala Ukończona'],
	},
	challenge: {
		title: ["Challenges", "Desafíos", "Défis", "Desafios", "Sfide", "Herausforderungen", "チャレンジ", "도전", "挑戰", "Wyzwania"],
		label: ["In Challenge","En desafío","En défi","Em desafio","In sfida","Im Herausforderungsmodus","チャレンジ中","도전 중","挑戰中", "W wyzwaniu"],
		start: ["Start", "Empezar", "Commencer", "Começar", "Inizia", "Starten", "開始", "시작", "開始", "Start"],
		on: ["On","Activado","Activé","Ligado","Acceso","An","オン","켬","開", "Włączone"],
		off: ["Off","Desactivado","Désactivé","Desligado","Spento","Aus","オフ","끔","關", "Wyłączone"],
		claim: [
		    "Claim",
		    "Reclamar",
		    "Réclamer",
		    "Reivindicar",
		    "Riscattare",
		    "Beanspruchen",
		    "受け取る",
		    "받기",
		    "领取",
		    "Odbierz"
		],
		claimed: [
		    "Claimed",
		    "Reclamado",
		    "Réclamé",
		    "Reivindicado",
		    "Riscattato",
		    "Beansprucht",
		    "受け取り済み",
		    "수령 완료",
		    "已领取",
		    "Odebrano"
		],
		surrender: [
		    "Surrender",
		    "Abandonar",
		    "Abandonner",
		    "Abandonar",
		    "Arresosi",
		    "Aufgeben",
		    "降参",
		    "항복",
		    "投降",
			"Poddaj się",
		],
		warning: [
		    "This is an experimental mode. There are no achievements or rewards for completing a challenge. Completed challenges are not saved. Closing the game will lose your challenge progress. Some challenges may be impossible to complete. You need 900 stars and at least 30 Pokémon to play challenges. Starting a challenge will reset your current progress in this route.",
		    "Esto es un modo experimental. No hay logros ni recompensas por terminar un desafío. Los desafíos completados no quedan guardados. Cerrar el juego pierde el progreso del desafío. Es posible que algunos desafíos sean imposibles de completar. Necesitas 900 estrellas y al menos 30 Pokémon para poder jugar desafíos. Al iniciar un desafío, perderás el progreso actual en esta ruta.",
		    "Ceci est un mode expérimental. Il n'y a ni succès ni récompenses pour terminer un défi. Les défis terminés ne sont pas sauvegardés. Quitter le jeu fera perdre la progression du défi. Certains défis peuvent être impossibles à compléter. Vous avez besoin de 900 étoiles et d'au moins 30 Pokémon pour jouer aux défis. Commencer un défi réinitialisera votre progression actuelle sur cette route.",
		    "Este é um modo experimental. Não há conquistas nem recompensas por concluir um desafio. Os desafios concluídos não são salvos. Fechar o jogo fará você perder o progresso do desafio. Alguns desafios podem ser impossíveis de completar. Você precisa de 900 estrelas e pelo menos 30 Pokémon para jogar desafios. Iniciar um desafio irá redefinir seu progresso atual nesta rota.",
		    "Questa è una modalità sperimentale. Non ci sono trofei né ricompense per completare una sfida. Le sfide completate non vengono salvate. Chiudere il gioco farà perdere i progressi della sfida. Alcune sfide potrebbero essere impossibili da completare. Hai bisogno di 900 stelle e di almeno 30 Pokémon per poter giocare le sfide. Avviando una sfida perderai i progressi attuali in questo percorso.",
		    "Dies ist ein experimenteller Modus. Es gibt keine Erfolge oder Belohnungen für das Abschließen einer Herausforderung. Abgeschlossene Herausforderungen werden nicht gespeichert. Das Schließen des Spiels führt zum Verlust des Fortschritts bei der Herausforderung. Einige Herausforderungen könnten unmöglich zu absolvieren sein. Du benötigst 900 Sterne und mindestens 30 Pokémon, um Herausforderungen zu spielen. Beim Starten einer Herausforderung geht dein aktueller Fortschritt auf dieser Route verloren.",
		    "これは実験モードです。チャレンジを完了しても実績や報酬はありません。完了したチャレンジは保存されません。ゲームを閉じるとチャレンジの進行状況は失われます。クリア不可能なチャレンジも存在する可能性があります。チャレンジをプレイするには、900個の星と少なくとも30匹のポケモンが必要です。チャレンジを開始すると、このルートでの現在の進行状況はリセットされます。",
		    "이것은 실험 모드입니다. 도전을 완료해도 업적이나 보상은 없습니다. 완료된 도전은 저장되지 않습니다. 게임을 종료하면 도전 진행 상황이 사라집니다. 일부 도전은 완료할 수 없을 수도 있습니다. 도전을 플레이하려면 900개의 별과 최소 30마리의 권속이 필요합니다. 도전을 시작하면 이 루트에서 현재 진행 상황이 초기화됩니다.",
		    "这是一个实验模式。完成挑战不会获得成就或奖励。已完成的挑战不会被保存。关闭游戏将丢失挑战进度。某些挑战可能无法完成。你需要900颗星和至少30只宝可梦才能进行挑战。开始挑战时，将会重置当前路线的进度。",
			"To tryb eksperymentalny. Za ukończenie wyzwania nie ma osiągnięć ani nagród. Ukończone wyzwania nie są zapisywane. Zamknięcie gry spowoduje utratę postępów w wyzwaniu. Niektórych wyzwań może nie dać się ukończyć. Aby grać w wyzwania, potrzebujesz 900 gwiazdek i co najmniej 30 Pokémonów. Rozpoczęcie wyzwania zresetuje Twoje bieżące postępy na tej trasie.",
		],
		egg: [
		  	"Contains a  Pokémon.",
		  	"Contiene un Pokémon.",
		  	"Contient un Pokémon.",
		  	"Contém um Pokémon.",
		  	"Contiene un Pokémon.",
		  	"Enthält ein Pokémon.",
		  	"ポケモンが入っている。",
		    "권속이 들어 있습니다.",
		    "包含一个宝可梦。",
			"Zawiera Pokémona.",
		],
		lvlCap: {
			title: [
				"Level Cap",
				"Límite nivel",
				"Niveau max",
				"Limite de nível",
				"Limite livello",
				"Level-Limit",
				"レベル の上限",
				"레벨 제한",
				"级上限",
				'Limit poziomu'
			],
			description:[
				"The maximum level of your Pokémon becomes limited",
				"El nivel máximo de tus Pokémon queda limitado",
				"Le niveau maximum de vos Pokémon est limité",
				"O nível máximo de seus Pokémon fica limitado",
				"Il livello massimo dei tuoi Pokémon è limitato",
				"Das maximale Level deiner Pokémon wird begrenzt",
				"ポケモンの最大レベルが制限される",
				"권속의 최대 레벨이 제한된다",
				"宝可梦的最高等级受到限制",
				"Maksymalny poziom twoich Pokémonów zostaje ograniczony"
			],
			level: [
				"level",
				"nivel",
				"niveau",
				"nível",
				"livello",
				"Level",
				"レベル",
				"레벨",
				"等级",
				"poziom"
			]
		},
		slotLimit: {
			title: [
				"Slot limit",
				"Límite de slots",
				"Limite de slots",
				"Limite de slots",
				"Limite slot",
				"Slotbegrenzung",
				"スロット上限",
				"슬롯 제한",
				"槽位上限",
				"Limit slotów"
			],
			description: [
				"The number of Pokémon you can carry becomes limited",
				"El número de Pokémon que puedes llevar queda limitado",
				"Le nombre de Pokémon que vous pouvez emporter est limité",
				"O número de Pokémon que você pode levar fica limitado",
				"Il numero di Pokémon che puoi portare è limitato",
				"Die Anzahl der Pokémon, die du mitnehmen kannst, ist begrenzt",
				"連れて行けるポケモンの数が制限される",
				"데려갈 수 있는 권속의 수가 제한된다",
				"可携带的宝可梦数量受到限制",
				"Liczba Pokémonów, które możesz zabrać, zostaje ograniczona"
			],
			slots: [
				"slots",
				"slots",
				"slots",
				"slots",
				"slot",
				"Slots",
				"スロット",
				"슬롯",
				"槽位",
				"sloty"
			]
		},
		toughEnemies: {
			title: [
				"Tough Enemies",
				"Enemigos resistentes",
				"Ennemis coriaces",
				"Inimigos fortes",
				"Nemici resistenti",
				"Starke Gegner",
				"タフな敵",
				"강한 적",
				"强敌",
				"Silniejsi Wrogowie"
			],
			description: [
				"The enemies have increased health and armor",
				"Los enemigos tienen la vida y armadura aumentada",
				"Les ennemis ont des points de vie et une armure augmentés",
				"Os inimigos têm vida e armadura aumentadas",
				"I nemici hanno salute e armatura aumentate",
				"Die Gegner haben erhöhte Lebenspunkte und Rüstung",
				"敵の体力と防御力が上昇している",
				"적들의 체력과 방어력이 증가했다",
				"敌人的生命值和护甲提高了",
				"Przeciwnicy mają zwiększone zdrowie i pancerz"
			]
		},
		draft: {
			title: [
				"Draft Pick",
				"Elección de Draft",
				"Choix de draft",
				"Escolha do Draft",
				"Scelta del Draft",
				"Draft-Auswahl",
				"ドラフトピック",
				"드래프트 픽",
				"选秀选择",
				"Wybór w Drafcie",
			],
			description: [
				"You will have to select your Pokémon team in a Draft phase at the start of the challenge.",
				"Tendrás que seleccionar tu equipo Pokémon en una fase de Draft al inicio del desafío.",
				"Vous devrez sélectionner votre équipe Pokémon dans une phase de draft au début du défi.",
				"Você terá que selecionar sua equipe de Pokémon em uma fase de Draft no início do desafio.",
				"Dovrai selezionare il tuo team Pokémon in una fase di Draft all'inizio della sfida.",
				"Du musst dein Pokémon-Team zu Beginn der Herausforderung in einer Draft-Phase auswählen.",
				"チャレンジ開始時に、ドラフトフェーズでポケモンチームを選択する必要があります。",
				"도전 시작 시 드래프트 단계에서 권속 팀을 선택해야 합니다.",
				"你需要在挑战开始时的选秀阶段选择你的宝可梦队伍。",
			"Na początku wyzwania musisz wybrać swoją drużynę Pokémonów w fazie draftu.",
			],
			round: [
				"Round",
				"Ronda",
				"Tour",
				"Rodada",
				"Turno",
				"Runde",
				"ラウンド",
				"라운드",
				"回合",
				"Runda",
			]
		},
		noItems: {
			title: ["No items", "Sin objetos", "Sans objets", "Sem itens", "Senza oggetti", "Ohne Gegenstände", "アイテムなし", "아이템 없음", "无道具", "Bez przedmiotów"],
			description: [
			    "You will not be able to equip items.",
			    "No podrás equipar objetos.",
			    "Vous ne pourrez pas équiper d'objets.",
			    "Você não poderá equipar itens.",
			    "Non potrai equipaggiare oggetti.",
			    "Du kannst keine Gegenstände ausrüsten.",
			    "アイテムを装備することはできません。",
			    "아이템을 장착할 수 없습니다.",
			    "你将无法装备道具。",
				"Nie będziesz mógł używać przedmiotów.",
			],
		},
		permadeath: {
			title: [
				"Permadeath",
				"Muerte permanente",
				"Mort permanente",
				"Morte permanente",
				"Morte permanente",
				"Permanenter Tod",
				"パーマデス",
				"영구 죽음",
				"永久死亡",
				"Permadeath"
			],
			description: [
				"Once you lose all lives, the challenge ends.",
				"Una vez pierdas todas las vidas, el desafío se termina.",
				"Une fois que vous perdez toutes vos vies, le défi se termine.",
				"Uma vez que você perca todas as vidas, o desafio termina.",
				"Una volta perse tutte le vite, la sfida termina.",
				"Sobald du alle Leben verlierst, endet die Herausforderung.",
				"すべてのライフを失うと、チャレンジは終了する。",
				"모든 생명을 잃으면 도전이 종료됩니다.",
				"一旦失去所有生命，挑战就结束。",
				"Po utracie wszystkich żyć, wyzwanie się kończy."
			],
		},
	},
	menu: {
		title: ['Menu', 'Menú', 'Menu', 'Menu', 'Menu', 'Menü', 'メニュー', '메뉴', '菜单', 'Menu'],
		version: {
			title: [
				"Version",
				"Versión",
				"Version",
				"Versão",
				"Versione",
				"Version",
				"バージョン",
				"버전",
				"版本",
				"Wersja"
			],
			checkUpdates: [
				"check for updates",
				"buscar actualizaciones",
				"rechercher des mises à jour",
				"procurar atualizações",
				"controlla gli aggiornamenti",
				"nach Updates suchen",
				"アップデートを確認する",
				"업데이트를 확인하다",
				"检查更新",
				"sprawdź aktualizacje"
			]
		},
		settings: {
			title: ['Settings', 'Opciones', 'Paramètres', 'Configurações', 'Impostazioni', 'Einstellungen', '設定', '설정', '设置', 'Ustawienia'],
			language: ['Language', 'Idioma', 'Langue', 'Idioma', 'Lingua', 'Sprache', '言語', '언어', '语言', 'Język'],
			audio: {
			    0: ['Volume Master', 'Volumen General', 'Volume Principal', 'Volume Geral', 'Volume Generale', 'Haupt-Lautstärke', 'マスター音量', '마스터 음량', '主音量', 'Główna Głośność'],
			    1: ['Volume Music', 'Volumen Música', 'Volume Musique', 'Volume Música', 'Volume Musica', 'Musiklautstärke', '音楽音量', '음악 음량', '音乐音量', 'Głośność Muzyki'],
			    2: ['Volume UI', 'Volumen Interfaz', 'Volume Interface', 'Volume Interface', 'Volume Interfaccia', 'UI-Lautstärke', 'UI音量', 'UI 음량', '界面音量', 'Głośność interfejsu'],
			    3: ['Volume Effects', 'Volumen Efectos', 'Volume Effets', 'Volume Efeitos', 'Volume Effetti', 'Effektlautstärke', '効果音量', '효과음 음량', '音效音量', 'Głośność efektów'],
			},
			mute: {
			    0: [
				  	"Mute projectiles",
				  	"Silenciar proyectiles",
				  	"Silencier projectiles",
				  	"Silenciar projéteis",
				  	"Silenziare proiettili",
				  	"Projektile stumm",
				  	"弾を無音にする",
				  	"발사체를 음소거",
				  	"使投射物静音",
				  	"Wyciszyć pociski"
				],
				1: [
					"Mute teleport",
				  	"Silenciar teleport",
				  	"Silencier teleport",
				  	"Silenciar teleport",
				  	"Silenziare teleport",
				  	"Teleport stumm",
				  	"テレポートを無音にする",
				  	"텔레포트를 음소거",
				  	"使瞬移静音",
				  	"Wycisz teleport"
				],
				2: [
				  	"Mute Shiny",
				  	"Silenciar Variocolor",
				  	"Silencier Chromatique",
				  	"Silenciar Brilhante",
				  	"Silenziare Lucente",
				  	"Schillernd stumm",
				  	"色違いを無音にする",
				  	"색이 다른 것을 음소거",
				  	"使色違い静音",
				  	"Wycisz Shiny"
				]
			},
			showDamage: ['Show Damage', 'Mostrar daño', 'Afficher dégâts', 'Mostrar dano', 'Mostra danno', 'Schaden anzeigen', 'ダメージ表示', '데미지 표시', '显示伤害', 'Pokaż Obrażenia'],
			showRoute: [
			  	'Always show route',
			  	'Mostrar la ruta',
			  	'Toujours la route',
			  	'Mostrar sempre a rota',
			  	'Mostra il percorso',
			  	'Route immer anzeigen',
			  	'常にルートを表示',
			  	'항상 경로 표시',
			  	'始终显示路线',
				'Zawsze pokazuj trasę',
			],
			showTC: [
			  	'Show tile count',
			  	'Conteo de casillas',
			  	'Afficher nb cases',
			  	'Contagem de casas',
			  	'Conteggio tessere',
			  	'Kachelanzahl anzeigen',
			  	'タイル数を表示',
			  	'타일 수 표시',
			  	'显示格子数量',
				'Pokaż liczbę pól'
			],
			autoReset: [
			  	'Auto Reset',
			  	'Reinicio automático',
			  	'Réinitialisation auto',
			  	'Reinicialização auto',
			  	'Ripristino automatico',
			  	'Auto Neustart',
			  	'自動リセット',
			  	'자동 재설정',
			  	'自动重置',
				'Automatyczny reset',
			],
			autoStop: [
			  	'Stop before invi.',
			  	'Detente ante invis.',
			  	'Stop av invi.',
			  	'Pare diante invi.',
			  	'Fermati davanti invi.',
			  	'Stopp vor Unsicht.',
			  	'見えない敵の前で止まれ',
			  	'보이지 않는 적 앞에서 멈춰',
			  	'在隐形敌人前停止',
				'Stój przed niewidz.',
			],
			autoStopBoss: [
			  	'Stop before boss',
			  	'Detener ante jefe',
			  	'Arrêter av. boss',
			  	'Parar diante chefe',
			  	'Fermarsi davanti boss',
			  	'Stopp vor Boss.',
			  	'ボスの前で停止',
			  	'보스 전에 정지',
			  	'在首领前停止',
				'Stój przed bossem',
			],
			displayHealth: [
			  	'Health Numbers',
			  	'Números de HP',
			  	'Numéros de PV',
			  	'Números de HP',
			  	'Numeri HP',
			  	'KP-Zahlen',
			  	'HP数値表示',
			  	'체력 숫자 표시',
			  	'显示生命值数字',
				'Liczby Zdrowia'
			],
			displayHealthOptions: {
				0: ["Off", "Apagado", "Désactivé", "Desligado", "Spento", "Aus", "オフ", "꺼짐", "关闭", "Wył."],
				1: ["Only Bosses", "Solo jefes", "Seulement les boss", "Apenas chefes", "Solo boss", "Nur Bosse", "ボスのみ", "보스만", "仅首领", "Tylko Bossowie"],
				2: ["Always", "Siempre", "Toujours", "Sempre", "Sempre", "Immer", "常に", "항상", "始终", "Zawsze"],
			},
			reset: {
				0: ['Off', 'Apagado', 'Arrêt', 'Desligado', 'Spento', 'Aus', 'オフ', '꺼짐', '关闭', 'Wył.'],
				1: ['Restart', 'Reiniciar', 'Recommencer', 'Reiniciar', 'Ricomincia', 'Neustarten', '再スタート', '재시작', '重新开始', 'Restart'],
				2: ['Retry', 'Reintentar', 'Réessayer', 'Tentar', 'Riprova', 'Wiederholen', '再試行', '재시도', '重试', 'Ponów'],
			},
			mapEffects: [
				"Map effects",
				"Efectos del mapa",
				"Effets de la carte",
				"Efeitos do mapa",
				"Effetti della mappa",
				"Karteneffekte",
				"マップ効果",
				"맵 효과",
				"地图效果",
				"Efekty mapy"
			],
			mapEffectsOptions: {
				0: [
					"Light",
					"Leves",
					"Légers",
					"Leves",
					"Leggeri",
					"Leicht",
					"軽度",
					"경미",
					"轻度",
					"Lekkie"
				],
				1: [
					"Total",
					"Total",
					"Total",
					"Total",
					"Totale",
					"Vollständig",
					"完全",
					"완전",
					"完全",
					"Całkowite"
				],
				2: [
					"Disabled",
					"Desactivado",
					"Désactivé",
					"Desativado",
					"Disattivato",
					"Deaktiviert",
					"無効",
					"비활성화",
					"已停用",
					"Wyłączone"
				]
			}
		},
		official: {
			title: [
				"Official Sites",
				"Sitios oficiales",
				"Sites officiels",
				"Sites oficiais",
				"Siti ufficiali",
				"Offizielle Seiten",
				"公式サイト",
				"공식 사이트",
				"官方网站",
				"Oficjalne strony"
			],
		},
		audio: {
			title: [
			  	"Audio",
			  	"Audio",
			  	"Audio",
			  	"Áudio",
			  	"Audio",
			  	"Audio",
			  	"オーディオ",
			  	"오디오",
			  	"音频",
			  	"Audio"
			]
		},
		shortcuts: {
			title: ['Keyboard Shortcuts', 'Atajos de Teclado', 'Raccourcis clavier', 'Atalhos de teclado', 'Scorciatoie da tastiera', 'Tastenkombinationen', 'キーボードショートカット', '키보드 단축키', '键盘快捷键', 'Skróty klawiszowe'],
		},
		credits: {
		 	title: ['Credits', 'Créditos', 'Crédits', 'Créditos', 'Crediti', 'Credits', 'クレジット', '크레딧', '制作人员', 'Twórcy'],
		},
		data: {
		 	title: ['Data', 'Datos', 'Données', 'Dados', 'Dati', 'Daten', 'データ', '데이터', '数据', 'Dane'],
		  	delete: ['Delete data', 'Borrar datos', 'Suppr. données', 'Apagar dados', 'Elimina dati', 'Daten löschen', 'データ削除', '데이터 삭제', '删除数据', 'Usuń dane'],
		  	import: ['Import data', 'Importar datos', 'Importer données', 'Importar dados', 'Importa dati', 'Daten importieren', 'データインポート', '데이터 가져오기', '导入数据', 'Importuj dane'],
			export: ['Export data', 'Exportar datos', 'Exporter données', 'Exportar dados', 'Esporta dati', 'Daten exportieren', 'データエクスポート', '데이터 내보내기', '导出数据', 'Eksportuj dane'],
		  	cancel: ['Back', 'Atrás', 'Retour', 'Voltar', 'Indietro', 'Zurück', '戻る', '뒤로', '返回', 'Wstecz'],
		  	deletePrompt: [
		  		'Are you sure you want to delete your progress?', 
		  		'¿Seguro que quieres borrar tu progreso?', 
		  		'Voulez-vous supprimer votre progression ?', 
		  		'Tem certeza de que deseja apagar seu progresso?', 
		  		'Sei sicuro di voler cancellare i tuoi progressi?', 
		  		'Bist du sicher, dass du deinen Fortschritt löschen möchtest?',
		  		'進行状況を削除してもよろしいですか？', 
		  		'진행 상황을 삭제하시겠습니까?',
		  		'你确定要删除你的进度吗？',
				'Czy na pewno chcesz usunąć swoje postępy?',
		  	],
		  	exportPrompt: [
		  	  	'Download your save as a .txt to have a backup or import the game to another device. Copy the code only as a last resort if you cannot download the file.',
		  	  	'Descarga tu partida como .txt para tener un respaldo o importar el juego a otro dispositivo. Copia el código solo como último recurso si no puedes descargar el archivo.',
		  	  	'Téléchargez votre sauvegarde au format .txt pour avoir une copie de sauvegarde ou importer le jeu sur un autre appareil. Copiez le code uniquement en dernier recours si vous ne pouvez pas télécharger le fichier.',
		  	  	'Baixe seu jogo como .txt para ter um backup ou importar o jogo para outro dispositivo. Copie o código apenas como último recurso se não puder baixar o arquivo.',
		  	  	'Scarica il tuo salvataggio come .txt per avere un backup o importare il gioco su un altro dispositivo. Copia il codice solo come ultima risorsa se non riesci a scaricare il file.',
		  	  	'Lade deinen Spielstand als .txt herunter, um ein Backup zu haben oder das Spiel auf ein anderes Gerät zu importieren. Kopiere den Code nur als letzte Möglichkeit, wenn du die Datei nicht herunterladen kannst.',
		  	  	'バックアップ用にセーブデータを.txtとしてダウンロードするか、別のデバイスにゲームをインポートしてください。ファイルをダウンロードできない場合のみ、コードをコピーしてください。',
		  	  	'백업을 위해 저장 데이터를 .txt로 다운로드하거나 게임을 다른 기기로 가져오세요. 파일을 다운로드할 수 없는 경우에만 코드를 복사하세요。',
		  	  	'将存档下载为 .txt 以便备份或在其他设备上导入游戏。只有在无法下载文件时才作为最后手段复制代码。',
				'Pobierz zapis jako plik .txt, aby mieć kopię zapasową lub zaimportować grę na inne urządzenie. Kod kopiuj tylko w ostateczności, jeśli nie możesz pobrać pliku.',
		  	],
		  	importPrompt: [
		  	  	'Upload your save here or paste your code to import your saved game (this will erase your current data).',
		  	  	'Sube aquí tu guardado o pega tu código para importar tu partida guardada (borrarás tus datos actuales).',
		  	  	'Téléversez votre sauvegarde ici ou collez votre code pour importer votre partie sauvegardée (cela effacera vos données actuelles).',
		  	  	'Envie seu save aqui ou cole seu código para importar sua partida salva (isso apagará seus dados atuais).',
		  	  	'Carica qui il tuo salvataggio o incolla il tuo codice per importare la partita salvata (questo cancellerà i tuoi dati attuali).',
		  	  	'Lade hier deinen Speicherstand hoch oder füge deinen Code ein, um dein gespeichertes Spiel zu importieren (dadurch werden deine aktuellen Daten gelöscht).',
		  	  	'ここにセーブをアップロードするか、保存したゲームをインポートするためにコードを貼り付けてください（現在のデータは消去されます）。',
		  	  	'여기에 세이브를 업로드하거나 저장된 게임을 가져오기 위해 코드를 붙여넣으세요(현재 데이터가 삭제됩니다)。',
		  	  	'在此上传存档或粘贴代码以导入已保存的游戏（这将清除你当前的数据）。',
				'Prześlij tu zapis lub wklej kod, aby zaimportować zapisaną grę (spowoduje to usunięcie obecnych danych).',
		  	],
		  	importButton: [
		  	  	'Load save',
		  	  	'Cargar partida',
		  	  	'Charger partie',
		  	  	'Carregar jogo',
		  	  	'Carica partita',
		  	  	'Spielstand laden',
		  	  	'セーブを読み込む',
		  	  	'저장 불러오기',
		  	  	'加载存档',
				'Wczytaj zapis',
		  	],
		  	uploadButton: [
		  	  	'Upload .txt',
		  	  	'Subir .txt',
		  	  	'Charger .txt',
		  	  	'Carregar .txt',
		  	  	'Carica .txt',
		  	  	'.txt hochladen',
		  	  	'.txt をアップロード',
		  	  	'.txt 업로드',
		  	  	'上传 .txt',
				'Prześlij .txt',
		  	],
			exportButton: [
			    "copy",
			    "copiar",
			    "copier",
			    "copiar",
			    "copiare",
			    "kopieren",
			    "コピー",
			    "복사",
			    "复制",
				"kopiuj",
			],
			downloadButton: [
			    "download",
			    "descargar",
			    "télécharger",
			    "baixar",
			    "scaricare",
			    "Herunterladen",
			    "ダウンロード",
			    "다운로드",
			    "下载",
				"pobierz",
			],
		  	importError: [
		  		'Incorrect code',
		  		'Código incorrecto', 
		  		'Code incorrect', 
		  		'Código incorreto', 
		  		'Codice errato', 
		  		'Falscher Code',
		  		'コードが正しくありません', 
		  		'잘못된 코드',
		  		'代码不正确',
				'Nieprawidłowy kod',
		  	],
		  	codeCopied: [
			  	'Code copied',
			  	'Código copiado',
			  	'Code copié',
			  	'Código copiado',
			  	'Codice copiato',
			  	'Code kopiert',
			  	'コードがコピーされました',
			  	'코드가 복사되었습니다',
			  	'代码已复制',
				'Skopiowano kod',
			],
			copyPlayerCode: [
				"Player code",
				"Código jugador",
				"Code joueur",
				"Código jogador",
				"Codice giocatore",
				"Spielercode",
				"プレイヤーコード",
				"플레이어 코드",
				"玩家代码",
				"Kod gracza"
			],
			redeemCodePlaceholder: [
				"Paste redeem code",
				"Pega el código de desbloqueo",
				"Collez le code de déblocage",
				"Cole o código de desbloqueio",
				"Incolla il codice di sblocco",
				"Freischaltcode einfügen",
				"アンロックコードを貼り付け",
				"해금 코드를 붙여넣기",
				"粘贴解锁代码",
				"Wklej kod odblokowania"
			],
			validateRedeem: [
				"Redeem",
				"Desbloquear",
				"Débloquer",
				"Desbloquear",
				"Sblocca",
				"Freischalten",
				"解放",
				"해금",
				"解锁",
				"Odblokuj"
			],
			redeemSuccess: [
				"Redeemed successfully",
				"Desbloqueado correctamente",
				"Déblocage réussi",
				"Desbloqueado com sucesso",
				"Sblocco riuscito",
				"Erfolgreich freigeschaltet",
				"解放に成功しました",
				"해금에 성공했습니다",
				"解锁成功",
				"Odblokowano pomyślnie"
			],
			redeemInvalidFormat: [
				"Invalid code",
				"Código inválido",
				"Code invalide",
				"Código inválido",
				"Codice non valido",
				"Ungültiger Code",
				"無効なコード",
				"잘못된 코드",
				"无效代码",
				"Nieprawidłowy kod"
			],
			redeemInvalidProfile: [
				"This code does not match this player code",
				"Este código no corresponde a este código de jugador",
				"Ce code ne correspond pas à ce code joueur",
				"Este código não corresponde a este código de jogador",
				"Questo codice non corrisponde a questo codice giocatore",
				"Dieser Code passt nicht zu diesem Spielercode",
				"このコードはこのプレイヤーコードと一致しません",
				"이 코드는 이 플레이어 코드와 일치하지 않습니다",
				"此代码与该玩家代码不匹配",
				"Ten kod nie pasuje do tego kodu gracza"
			],
			redeemAlreadyOwned: [
				"Already redeemed",
				"Ya desbloqueado",
				"Déjà débloqué",
				"Já desbloqueado",
				"Già sbloccato",
				"Bereits freigeschaltet",
				"すでに解放済みです",
				"이미 해금되었습니다",
				"已解锁",
				"Już odblokowane"
			],
			redeemUnavailable: [
				"This redeem is not available in this version",
				"Este desbloqueo no está disponible en esta versión",
				"Ce déblocage n'est pas disponible dans cette version",
				"Este desbloqueio não está disponível nesta versão",
				"Questo sblocco non è disponibile in questa versione",
				"Diese Freischaltung ist in dieser Version nicht verfügbar",
				"このアンロックはこのバージョンでは利用できません",
				"이 해금은 이 버전에서 사용할 수 없습니다",
				"此版本不提供该解锁内容",
				"To odblokowanie nie jest dostępne w tej wersji"
			]
		},
	},
	defeat: {
	  	title: ['Game Over', 'Derrota', 'Défaite', 'Derrota', 'Sconfitta', 'Niederlage', 'ゲームオーバー', '패배', '游戏结束', 'Koniec gry'],
  		prompt: ['You have survived a total of ', 'Has sobrevivido un total de ', 'Vous avez survécu un total de ', 'Você sobreviveu por um total de ', 'Hai sopravvissuto per un totale di ', 'Du hast insgesamt überlebt: ', '合計で生き延びた時間: ', '총 생존 시간: ', '你总共生存了 ', 'Łączny czas przetrwania: '],
  		restart: ['Restart', 'Reiniciar', 'Recommencer', 'Reiniciar', 'Ricomincia', 'Neustarten', '再スタート', '재시작', '重新开始', 'Restart'],
  		retry: ['Retry', 'Reintentar', 'Réessayer', 'Tentar', 'Riprova', 'Wiederholen', '再試行', '재시도', '重试', 'Ponów'],
  		promptChallengeLost:[
			"Permadeath was enabled, so the challenge has failed.",
			"Muerte permanente activada, el desafío ha fracasado.",
			"La mort permanente était activée, le défi a donc échoué.",
			"A morte permanente estava ativada, portanto o desafio falhou.",
			"La morte permanente era attiva, quindi la sfida è fallita.",
			"Permanenter Tod aktiviert, die Herausforderung ist gescheitert.",
			"パーマデスが有効だったため、チャレンジは失敗した。",
			"퍼마데스가 활성화되어 있었기 때문에 도전은 실패했습니다.",
			"永久死亡已启用，因此挑战失败了。",
			"Permadeath był włączony, więc wyzwanie zakończyło się niepowodzeniem."
		],
	  	cantRetry: [
		    'You must clear at least 25 waves to unlock the retry option',
		    'Necesitas superar 25 oleadas para desbloquear reintentar',
			'Vous devez dépasser 25 vagues pour débloquer la possibilité de réessayer',
			'Você precisa superar 25 ondas para desbloquear repetir',
			'Devi superare 25 ondate per sbloccare riprova',
			'Du musst mindestens 25 Wellen schaffen, um „Wiederholen“ freizuschalten',
		    '再試行オプションを解放するには、最低25ウェーブをクリアする必要があります',
		    '재시도 옵션을 해제하려면 최소 25웨이브를 넘어야 합니다',
		    '你必须至少通关25波以解锁重试选项',
	   	 	'Musisz ukończyć co najmniej 25 fal, aby odblokować opcję ponowienia'
		],
	},
	final: {
		title: ['End of route', 'Fin de ruta', 'Fin de la route', 'Fim da rota', 'Fine del percorso', 'Routenende', 'ルート終了', '루트 끝', '路线结束', 'Koniec drogi'],
		prompt: ['Route completed!', '¡Ruta completada!', 'Route terminée !', 'Rota concluída!', 'Percorso completato!', 'Route abgeschlossen!', 'ルートクリア！', '루트 완료!', '路线完成！', 'Droga ukończona!'],
		accept: ['Completed', 'Completado', 'Terminé', 'Completo', 'Completato', 'Abgeschlossen', '完了', '완료', '已完成', 'Ukończono'],
	},
	newGame: {
	  	title: ['Profile Creation', 'Creación de perfil', 'Création de profil', 'Criação de perfil', 'Creazione profilo', 'Profilerstellung', 'プロフィール作成', '프로필 생성', '创建个人资料', 'Tworzenie profilu'],
	  	start: ['Start', 'Comenzar', 'Commencer', 'Começar', 'Avvia', 'Starten', 'スタート', '시작', '开始', 'Start'],
	},
	endGame: {
	  	title: ["All routes conquered", "Todas las rutas conquistadas", "Toutes les routes conquises", "Todas as rotas dominadas", "Tutte le rotte conquistate", "Alle Routen gemeistert", "全ルート制覇", "모든 루트 정복", '所有路线已征服', 'Wszystkie trasy zdobyte'],
	  	accept: ['Completed', 'Completado', 'Terminé', 'Completo', 'Completato', 'Abgeschlossen', '完了', '완료', '已完成', 'Ukończono'],
	},
	tutorial: {
		title: ['Tutorial', 'Tutorial', 'Tutoriel', 'Tutorial', 'Tutorial', 'Tutorial', 'チュートリアル', '튜토리얼', '教程', 'Samouczek'],
		next: ['Next', 'Siguiente', 'Suivant', 'Próximo', 'Avanti', 'Weiter', '次へ', '다음', '下一步', 'Dalej'],
		back: ['Back', 'Atrás', 'Retour', 'Voltar', 'Indietro', 'Zurück', '戻る', '뒤로', '返回', 'Wstecz'],
		end: ['End', 'Terminar', 'Fin', 'Fim', 'Fine', 'Ende', '終了', '끝', '结束', 'Koniec'],
	},
}

export function formatNumberWithCommas(num) {
    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
